### ISSUE TITLE
Extract tarballs in gtz and romana/home/hal/r10 into separate repos

### ISSUE THREAD

**Issue by zhuowei** [opless/mwc-mwc#1]
Since a bunch of stuff is in the tarballs in the gtz folder, it might be useful to extract each into separate repos to make them searchable. e.g. src.gtz has a src/sys.r12 folder that looks like the kernel source, and romama/home/hal/r10 has tarballs of for what looks like 4.2.10's source

**Comment by zhuowei** [comment]
Also there's a few RCS repos on romana (e.g. romana/relic/d/286_KERNEL) with version history; is it possible to convert them to Git repos?

**Comment by opless** [comment]
Thank you zhuowei for your messages on here and twitter.

It might be useful, but it seems wasteful as this is just an archive. 

I might get around to it one day, but that day isn't in the immediate or near future.
